### ISSUE TITLE
'idlist': give the caller a chance to tell us how to store the values.

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.TinyWKB#1]
Currently, `TinyWkbWriter` only supports two ways of writing out `idlist` values: either **all** included `Geometry` values must have `UserData` be convertible to `long`, or we'll just fall back to using auto-generated values fed from a static field.

`TinyWkbReader` automatically sets the `UserData` values to make a round-trip work in simple cases.

This has a few problems:
1. If the `GeometryFactory` is a subclass that already sets something application-specific in the `UserData`, then `TinyWkbReader` will clobber what they did.  An example might be if the factory translates the results to some other coordinate system and caches them in `UserData`.
1. Related to the previous one, if the user does **anything** with `UserData` (other than, of course, exactly what we do), then they'll clobber this ID, perhaps unknowingly.
1. This behavior is not very discoverable.  Core NTS very rarely touches `UserData` except to copy the object reference around (by design).

**Comment by airbreather** [comment]
One way to deal with this (probably a breaking change) could be to use `NetTopologySuite.Features` to hold the ID, which would also support other things that get added to the spec in the future.

To avoid breaking things that work today, we could add a new event on `TinyWkbReader` and a new event on `TinyWkbWriter` that the user can subscribe to in order to tell us how to translate between `UserData` and the `long` that we read / generate.

Using that event when reading geometries:
```csharp
GeometryCollection gc = /* ... */;
long[] idList = /* ... */;

EventHandler<EventArgsSubclass> handler = this.TheNewEvent;
if (handler != null)
{
    EventArgsSubclass args = new EventArgsSubclass(gc, idList);
    handler(this, args);
}
else
{
    for (int i = 0; i < gc.NumGeometries; i++)
    {
        gc.GetGeometryN(i).UserData = idList[i];
    }
}
```

Using that event when writing geometries:
```csharp

BinaryWriter writer = /* ... */;
GeometryCollection gc = /* ... */;

EventHandler<EventArgsSubclass> handler = this.TheNewEvent;
long[] idList;
if (handler != null)
{
    EventArgsSubclass args = new EventArgsSubclass(gc);
    handler(this, args);
    idList = args.IdList.ToArray();
}
else
{
    idList = new long[gc.Count];
    bool fallback = false;
    for (int i = 0; i < idList.Length; i++)
    {
        object userData = gc.GetGeometryN(i).UserData;
        if (userData is null)
        {
            fallback = true;
            break;
        }

        try
        {
            idList[i] = Convert.ToInt64(userData, CultureInfo.InvariantCulture);
        }
        catch
        {
            fallback = true;
            break;
        }
    }

    if (fallback)
    {
        for (int i = 0; i < idList.Length; i++)
        {
            idList[i] = GetNextId();
        }
    }
}
```

We'd keep the exact same behavior by default, but the user could then tell us how they want to store their own IDs and we would honor that.

**Comment by FObermaier** [comment]
Note: 
1. This project is not that old.
2. The download numbers on NuGet are not that high, too.

I'm not too concerned about breaking backward compatibility, so if there is a different approach to handle this that you actually favor, then I don't have a problem with it.
